export const AppRoutingPaths = {
    AYUDA_EXTERIOR: "/help-ext",
    AYUDA_INTERIOR: "/help",
    BIBLIOTECA: "/biblioteca",
    BLANK: "",
    CALENDARIO: "/calendario",
    CALIFICACIONES: "/calificaciones",
    CURSOS_ACTIVOS: "/cursos-activos",
    CURSOS_ACTIVOS_DETALLES: "/cursos-detalles/:id",
    CURSOS_CERTIFICACIONES: "/cursos-certificaciones",
    ERROR: "/error",
    HOME: "/",
    LOGIN: "/login",
    MI_PERFIL: "/mi-perfil",
    MI_PERFIL_EDIT: "/edit-perfil",
    NOTFOUND: '*',
    PREGUNTAS_FRECUENTES: "/faqs-ext",
    PREGUNTAS_FRECUENTES_INT: "/faqs",
    PLAN_ESTUDIOS: "/plan-estudios",
    SALA_CONVERSACIONES: "/sala",
    VIDEOS_LECTURAS: "/videos",
    SERVICIOS_ESCOLORES: "/serv-esco",
    CONTACTO: "/contact",
    MANUAL_INDUCCION: "/manual",
    PLAN_ESTUDIO_INFORMACION: "/plan-estudios/info/:id",
    CONSEJERIA: "/consejeria",
    BOLETIN_EDUCATIVO: "/boletin",
    CERTIFICACIONES: "/cert",
    BOLSA_TRABAJO: "/bolsa-trab",
    PIZARRON: "/pizarron",
    MI_TRAYECTO: "/mi-trayecto",
    TERMINOS_CONDICIONES: "/terminos-condiciones",
    VIDEOTECA_DETALLE: "/videoteca",
    APRENDE_MAS: "/aprende-mas",
    CALIFICACIONES_DETALLE: "/calificacion/detalle/:id",
    FOROS: "/foros",
    NOSOTROS: "/nosotros",
    AGENDA_CITA: "/agenda-cita",
    CONSEJERIA_BLOG: "/blog",
    NOTIFICACIONES: "/notificaciones",

} as const;

export type AppRoutingPaths = typeof AppRoutingPaths;

export const TitleScreen = {
    AYUDA: "Ayuda",
    BIBLIOTECA: "Biblioteca",
    BIBLIOTECA_VIRTUAL: "Biblioteca virtual",
    CALENDARIO: "Calendario",
    CALIFICACIONES: "Calificaciones",
    CURSOS_ACTIVOS: "Cursos Activos",
    CURSOS_CERTIFICACIONES: "Cursos y certificaciones",
    HOME: "Inicio",
    MI_PERFIL: "Mi Perfil",
    PLAN_ESTUDIOS: "Plan de estudios",
    PREGUNTAS_FRECUENTES: "Preguntas Frecuentes",
    SALA_CONVERSACIONES: "Sala de conversación",
    VIDEOS_LECTURAS: "Videos y Lecturas de interés",
    SERVICIOS_ESCOLORES: "Servicios Escolares",
    CONTACTO: "Contacto",
    MANUAL_INDUCCION: "Manual de inducción",
    LINEAMIENTOS: "Lineamientos",
    FAQS: "Faqs",
    BACK_HOME_EXT: "Regresar a inicio",
    NUEVA_SOLICITUD: "Nueva Solicitud",
    CONSEJERIA: "Consejería estudiantil",
    BOLETIN_EDUCATIVO: "Boletín Educativo",
    CERTIFICACIONES: "Certificaciones",
    BOLSA_TRABAJO: "Bolsa de Trabajo",
    PIZARRON: "Pizarron del éxito",
    MI_TRAYECTO: "Mi Trayecto",
    APRENDE_MAS: "Aprende Más",
    TERMINOS_CONDICIONES: "Términos y Condiciones",
    MANUALES_USUARIOS: "Manuales de Usuario",
}

export type TitleScreen = typeof TitleScreen;