export const ModulosCampusIds = {
    PLAN_ESTUDIO: 1,
    CURSOS_ACTIVOS: 2,
    CALENDARIO: 3,
    SALA_CONVERSACION: 4,
    BIBLIOTECA: 5,
    CONSEJERIA_ESTUDIANTIL: 6,
    CALIFICACIONES: 11,
    SERVICIOS_ESCOLARES: 12,
}