export { default as Home } from './pages/Home/Home';
export { default as Calificaciones } from './pages/Calificaciones/Calificaciones';
export { default as MiTrayecto } from './pages/MiTrayecto/MiTrayecto';
export { default as NotFound } from './pages/NotFound/NotFound';
export { default as ToDo } from './pages/ToDo/ToDo';
export { default as PreguntasFrecuentes } from './pages/PreguntasFrecuentes/PreguntasFrecuentes';
export { default as AyudaLogin } from './pages/ayuda/AyudaLogin';
export { default as MainTemplate } from './templates/MainTemplate/MainTemplate';
export { default as LoginPage } from './pages/Login/Login';
export { default as ServiciosEscolares } from './pages/ServiciosEscolares/ServiciosEscolares';
export { default as Calendario } from './pages/Calendario/Calendario';
export { default as PlanEstudio } from './pages/PlanEstudio/PlanEstudio';
export { default as CursoActivo } from './pages/CursosActivos/CursosActivos';
export { default as CursosActivosDetalles } from './pages/CursosActivosDetalles/CursosActivosDetalles';
export { default as CurosCertificaciones } from './pages/CurosCertificaciones/CurosCertificaciones';
export { default as Certificaciones } from './pages/Certificaciones/Certificaciones';
export { default as VideotecaBiblioteca } from './pages/VideotecaBiblioteca/VideotecaBiblioteca';
export { default as MiPerfil } from './pages/MiPerfil/MiPerfil';
export { default as Ayuda } from './pages/ayuda/Ayuda';
export { default as PreguntasFrecuentesInternas } from './pages/PreguntasFrecuentes/PreguntasFrecuentesInternas';
export { default as SalaConversacion } from './pages/SalaConversacion/SalaConversacion';

export * as Organisms from './organisms';