name: Deploy to Develop

on:
  push:
    branches: [ develop ]

env:
  AWS_REGION: us-east-2
  AWS_ROLE: arn:aws:s3:::desplieguegit
  S3_BUCKET: arn:aws:s3:::desplieguegit

permissions:
  id-token: write
  contents: read

jobs:
    build-and-deploy:
        name: Deploy ${{ github.ref_name }} to develop
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        # - name: Configure AWS credentials
        #   uses: aws-actions/configure-aws-credentials@v4.1.0
        #   with:
        #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #     aws-region: ${{ env.AWS_REGION }}
        #     role-to-assume: ${{ env.AWS_ROLE }}

        # Instala dependencias (ajusta según tu proyecto)
        - name: Install dependencies
          run: npm install

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20' # Usa la versión que necesites
            cache: 'npm'

        - name: Install dependencies
          run: npm install

        # Construye el proyecto (ajusta según tu proyecto)
        - name: Build project
          run: npm run build

        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: './dist'

        - name: Deploy to GitHub Pages
          uses: actions/deploy-pages@v4


        # - name: Copy to S3
        #   run: |
        #     aws s3 sync ./dist s3://${{env.S3_BUCKET}} --delete --only-show-errors

        # Publica o despliega (ajusta este paso según tu flujo)
        - name: Deploy to Develop Environment
          run: echo "Deploying to develop environment..."
                # Aquí puedes agregar comandos de despliegue reales, por ejemplo:
                # run: npm run deploy:dev